# Production Stage - Using pre-built frontend
FROM docker.m.daocloud.io/nginx:alpine AS production-stage
COPY frontend/dist /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
